#!/usr/bin/env bash
set -Eeuo pipefail

export PGHOST="${POSTGRES_HOST:-postgres}"
export PGPORT="${POSTGRES_PORT:-5432}"

verify_service() {
  local service="$1"
  local database_var="${service^^}_DB"
  local app_user_var="${service^^}_APP_USER"
  local app_password_var="${service^^}_APP_PASSWORD"
  local migrator_user_var="${service^^}_MIGRATOR_USER"
  local migrator_password_var="${service^^}_MIGRATOR_PASSWORD"
  local database="${!database_var}"
  local app_user="${!app_user_var}"
  local app_password="${!app_password_var}"
  local migrator_user="${!migrator_user_var}"
  local migrator_password="${!migrator_password_var}"

  PGUSER="$app_user" PGPASSWORD="$app_password" \
    psql --dbname="$database" --set=ON_ERROR_STOP=1 --command='SELECT 1' >/dev/null

  if PGUSER="$app_user" PGPASSWORD="$app_password" \
    psql --dbname="$database" --set=ON_ERROR_STOP=1 \
      --command='CREATE TABLE public._relay_app_ddl_probe (id integer)' >/dev/null 2>&1; then
    PGUSER="$app_user" PGPASSWORD="$app_password" \
      psql --dbname="$database" --command='DROP TABLE public._relay_app_ddl_probe' >/dev/null 2>&1 || true
    printf 'Application role %s unexpectedly has DDL privileges in %s\n' "$app_user" "$database" >&2
    exit 1
  fi

  PGUSER="$migrator_user" PGPASSWORD="$migrator_password" \
    psql --dbname="$database" --set=ON_ERROR_STOP=1 >/dev/null <<'SQL'
DROP TABLE IF EXISTS public._relay_dml_probe;
CREATE TABLE public._relay_dml_probe (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  value text NOT NULL DEFAULT ''
);
SQL
  PGUSER="$app_user" PGPASSWORD="$app_password" \
    psql --dbname="$database" --set=ON_ERROR_STOP=1 \
      --command="INSERT INTO public._relay_dml_probe DEFAULT VALUES; SELECT id, value FROM public._relay_dml_probe; UPDATE public._relay_dml_probe SET value = 'verified'; DELETE FROM public._relay_dml_probe;" >/dev/null
  PGUSER="$migrator_user" PGPASSWORD="$migrator_password" \
    psql --dbname="$database" --set=ON_ERROR_STOP=1 \
      --command='DROP TABLE public._relay_dml_probe' >/dev/null

  PGUSER="$migrator_user" PGPASSWORD="$migrator_password" \
    psql --dbname="$database" --set=ON_ERROR_STOP=1 >/dev/null <<'SQL'
DROP TABLE IF EXISTS goose._relay_metadata_probe;
CREATE TABLE goose._relay_metadata_probe (id integer PRIMARY KEY);
SQL
  if PGUSER="$app_user" PGPASSWORD="$app_password" \
    psql --dbname="$database" --set=ON_ERROR_STOP=1 \
      --command='SELECT * FROM goose._relay_metadata_probe' >/dev/null 2>&1; then
    PGUSER="$migrator_user" PGPASSWORD="$migrator_password" \
      psql --dbname="$database" --command='DROP TABLE goose._relay_metadata_probe' >/dev/null 2>&1 || true
    printf 'Application role %s unexpectedly accessed migration metadata in %s\n' "$app_user" "$database" >&2
    exit 1
  fi
  PGUSER="$migrator_user" PGPASSWORD="$migrator_password" \
    psql --dbname="$database" --set=ON_ERROR_STOP=1 \
      --command='DROP TABLE goose._relay_metadata_probe' >/dev/null

  local other
  for other in content delivery identity processing; do
    [ "$other" = "$service" ] && continue
    local other_database_var="${other^^}_DB"
    local other_database="${!other_database_var}"
    if PGUSER="$app_user" PGPASSWORD="$app_password" \
      psql --dbname="$other_database" --command='SELECT 1' >/dev/null 2>&1; then
      printf 'Application role %s unexpectedly connected to %s\n' "$app_user" "$other_database" >&2
      exit 1
    fi
    if PGUSER="$migrator_user" PGPASSWORD="$migrator_password" \
      psql --dbname="$other_database" --command='SELECT 1' >/dev/null 2>&1; then
      printf 'Migrator role %s unexpectedly connected to %s\n' "$migrator_user" "$other_database" >&2
      exit 1
    fi
  done

  printf 'Database isolation verified for %s\n' "$service"
}

for service in content delivery identity processing; do
  verify_service "$service"
done
