// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: relay/identity/v1/identity.proto

package identityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IntrospectRequest carries an opaque user access token.
type IntrospectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectRequest) Reset() {
	*x = IntrospectRequest{}
	mi := &file_relay_identity_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectRequest) ProtoMessage() {}

func (x *IntrospectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_identity_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectRequest.ProtoReflect.Descriptor instead.
func (*IntrospectRequest) Descriptor() ([]byte, []int) {
	return file_relay_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *IntrospectRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// IntrospectResponse identifies a valid current user and session.
type IntrospectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectResponse) Reset() {
	*x = IntrospectResponse{}
	mi := &file_relay_identity_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectResponse) ProtoMessage() {}

func (x *IntrospectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_identity_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectResponse.ProtoReflect.Descriptor instead.
func (*IntrospectResponse) Descriptor() ([]byte, []int) {
	return file_relay_identity_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *IntrospectResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *IntrospectResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IntrospectResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ValidateCSRFRequest carries the access and CSRF tokens from a mutation.
type ValidateCSRFRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	CsrfToken     string                 `protobuf:"bytes,2,opt,name=csrf_token,json=csrfToken,proto3" json:"csrf_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCSRFRequest) Reset() {
	*x = ValidateCSRFRequest{}
	mi := &file_relay_identity_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCSRFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCSRFRequest) ProtoMessage() {}

func (x *ValidateCSRFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_identity_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCSRFRequest.ProtoReflect.Descriptor instead.
func (*ValidateCSRFRequest) Descriptor() ([]byte, []int) {
	return file_relay_identity_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateCSRFRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ValidateCSRFRequest) GetCsrfToken() string {
	if x != nil {
		return x.CsrfToken
	}
	return ""
}

// ValidateCSRFResponse distinguishes a revoked session from a bad CSRF token.
type ValidateCSRFResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessValid   bool                   `protobuf:"varint,1,opt,name=access_valid,json=accessValid,proto3" json:"access_valid,omitempty"`
	CsrfValid     bool                   `protobuf:"varint,2,opt,name=csrf_valid,json=csrfValid,proto3" json:"csrf_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCSRFResponse) Reset() {
	*x = ValidateCSRFResponse{}
	mi := &file_relay_identity_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCSRFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCSRFResponse) ProtoMessage() {}

func (x *ValidateCSRFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_identity_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCSRFResponse.ProtoReflect.Descriptor instead.
func (*ValidateCSRFResponse) Descriptor() ([]byte, []int) {
	return file_relay_identity_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateCSRFResponse) GetAccessValid() bool {
	if x != nil {
		return x.AccessValid
	}
	return false
}

func (x *ValidateCSRFResponse) GetCsrfValid() bool {
	if x != nil {
		return x.CsrfValid
	}
	return false
}

var File_relay_identity_v1_identity_proto protoreflect.FileDescriptor

const file_relay_identity_v1_identity_proto_rawDesc = "" +
	"\n" +
	" relay/identity/v1/identity.proto\x12\x11relay.identity.v1\"6\n" +
	"\x11IntrospectRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"b\n" +
	"\x12IntrospectResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"W\n" +
	"\x13ValidateCSRFRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"csrf_token\x18\x02 \x01(\tR\tcsrfToken\"X\n" +
	"\x14ValidateCSRFResponse\x12!\n" +
	"\faccess_valid\x18\x01 \x01(\bR\vaccessValid\x12\x1d\n" +
	"\n" +
	"csrf_valid\x18\x02 \x01(\bR\tcsrfValid2\xcd\x01\n" +
	"\x0fIdentityService\x12Y\n" +
	"\n" +
	"Introspect\x12$.relay.identity.v1.IntrospectRequest\x1a%.relay.identity.v1.IntrospectResponse\x12_\n" +
	"\fValidateCSRF\x12&.relay.identity.v1.ValidateCSRFRequest\x1a'.relay.identity.v1.ValidateCSRFResponseBJZHgithub.com/horizoonn/relay/shared/pkg/proto/relay/identity/v1;identityv1b\x06proto3"

var (
	file_relay_identity_v1_identity_proto_rawDescOnce sync.Once
	file_relay_identity_v1_identity_proto_rawDescData []byte
)

func file_relay_identity_v1_identity_proto_rawDescGZIP() []byte {
	file_relay_identity_v1_identity_proto_rawDescOnce.Do(func() {
		file_relay_identity_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_identity_v1_identity_proto_rawDesc), len(file_relay_identity_v1_identity_proto_rawDesc)))
	})
	return file_relay_identity_v1_identity_proto_rawDescData
}

var file_relay_identity_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_relay_identity_v1_identity_proto_goTypes = []any{
	(*IntrospectRequest)(nil),    // 0: relay.identity.v1.IntrospectRequest
	(*IntrospectResponse)(nil),   // 1: relay.identity.v1.IntrospectResponse
	(*ValidateCSRFRequest)(nil),  // 2: relay.identity.v1.ValidateCSRFRequest
	(*ValidateCSRFResponse)(nil), // 3: relay.identity.v1.ValidateCSRFResponse
}
var file_relay_identity_v1_identity_proto_depIdxs = []int32{
	0, // 0: relay.identity.v1.IdentityService.Introspect:input_type -> relay.identity.v1.IntrospectRequest
	2, // 1: relay.identity.v1.IdentityService.ValidateCSRF:input_type -> relay.identity.v1.ValidateCSRFRequest
	1, // 2: relay.identity.v1.IdentityService.Introspect:output_type -> relay.identity.v1.IntrospectResponse
	3, // 3: relay.identity.v1.IdentityService.ValidateCSRF:output_type -> relay.identity.v1.ValidateCSRFResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relay_identity_v1_identity_proto_init() }
func file_relay_identity_v1_identity_proto_init() {
	if File_relay_identity_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_identity_v1_identity_proto_rawDesc), len(file_relay_identity_v1_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relay_identity_v1_identity_proto_goTypes,
		DependencyIndexes: file_relay_identity_v1_identity_proto_depIdxs,
		MessageInfos:      file_relay_identity_v1_identity_proto_msgTypes,
	}.Build()
	File_relay_identity_v1_identity_proto = out.File
	file_relay_identity_v1_identity_proto_goTypes = nil
	file_relay_identity_v1_identity_proto_depIdxs = nil
}
